import Head from 'next/head'
import { useEffect, useState } from 'react'
import Image from 'next/image'
import Carousel from '../src/Components/Carousel'
import { AnimatePresence, motion } from 'framer-motion'
import CarouselItem from '../src/Components/CarouselItem'
import axios from 'axios'

const images = [
  {
    title: "Demon Slayer",
    image: "/zen-dark.jpg"
  },
  {
    title: "Attack On titan",
    image: "/zenitsu.jpg"
  },
  {
    title: "Naruto",
    image: "/stand.jpg"
  }
]

export default function Home() {

  const [current, setCurrent] = useState(0)
  const [active, setActive] = useState(null)
  const [data, setData] = useState([])

  useEffect(() => {
    axios.get("https://api.jikan.moe/v4/top/anime")
      .then(response => {
        console.log(response.data.data)
        setData(response.data.data)
      })
  }, [])


  const prev = () => {
    if (current <= 0) {
      setCurrent(data?.length - 1)
    } else {
      setCurrent(current - 1)
    }
  }

  const next = () => {
    if (current >= data?.length - 1) {
      setCurrent(0)
    } else {
      setCurrent(current + 1)
    }
  }
  return (
    <div className='w-full h-screen overflow-y-scroll ' >
      <Head>
        <title>Anime Stream</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className='w-full h-full' >
        <AnimatePresence>
          {
            (active == null) && (
              <motion.button
                className="prev"
                onClick={prev} >
                prev
              </motion.button>
            )
          }
        </AnimatePresence>
        <div className='w-full h-full flex flex-nowrap overflow-hidden relative'>
          {
            data?.map((item, index) => (
              <CarouselItem item={item} key={index} show={current === index} active={active === index} />
            ))
          }
        </div>
        <AnimatePresence>
          {
            (active == null) && (
              <motion.button
                className="next"
                onClick={next} >
                next
              </motion.button>
            )
          }
        </AnimatePresence>
      </main>
      {/* <Carousel /> */}
      {
        (active == null) && (
          <section className='w-full h-full fixed z-20 top-0 left-0 bg-black/20 flex flex-col justify-end p-10 gap-5' >
            <div className='flex flex-col justify-end gap-20' >
              <div className="flex flex-col gap-3" >
                <div className="flex gap-3" >
                  {
                    data[current]?.genres.map((genre) => (
                      <div className='bg-blur' key={genre?.mal_id} >
                        {genre?.name}
                      </div>
                    ))
                  }
                </div>
                <div>
                  <motion.p className='large-text'
                    initial={{
                      y: "10%"
                    }}
                    animate={{
                      y: "0%"
                    }}
                    exit={{
                      y: "-10%"
                    }}
                  >
                    {data[current]?.title}
                  </motion.p>
                </div>
                <div className='medium-text' >
                  {data[current]?.type}
                </div>
                <div
                  className='w-fit flex gap-2 items-center'
                  onClick={() => setActive(current)}
                >
                  <button className='primary-btn py-4' >
                    <div className='icon' >
                      <Image src="/play.png" alt="Image" layout='fill' className='object-cover' />
                    </div>
                  </button>
                  <p className='small-text' >
                    Watch Now
                  </p>
                </div>
              </div>
            </div>
            <div className='w-full flex justify-between items-end' >
              <div className='w-fit flex justify-start gap-2 items-end'>
                <div className='w-16 h-28 bg-blur' />
                <p>
                  {data[current]?.year}
                </p>
                <p>
                  {data[current]?.episodes} Episodes
                </p>
              </div>
              <div className='w-40 h-40 bg-blur relative overflow-hidden' >
                <button className='primary-btn py-4 absolute top-3 left-3 z-10'>
                  <div className='icon' >
                    <Image src="/play.png" alt="Image" layout='fill' className='object-cover' />
                  </div>
                </button>
                <Image src={data[current]?.trailer.images.image_url} alt="Image" layout='fill' className='object-cover' />
              </div>
            </div>
          </section>
        )
      }
    </div>
  )
}

